# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: "%env(APP_SECRET)%"
    trusted_hosts: ["amicale-rca.onrender.com", "localhost", "127.0.0.1"]

    # Note that the session will be started ONLY if you read or write from it.
    session: true

when@prod:
    framework:
        router:
            default_uri: "https://amicale-rca.onrender.com"

    #esi: true
    #fragments: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
