#!/bin/bash

# Script de test pour vérifier les deux features:
# 1. Montant colonne indépendant des filtres
# 2. Collapse/expand des exercices

echo "===== TEST DES FEATURES DE TRANSACTION ====="
echo ""
echo "1. TEST MONTANT COLONNE (indépendant des filtres)"
echo "   Action: Accéder à /transaction sans filtre"
echo "   Résultat attendu: Montant cumulé correct"
echo "   Vérifier: https://amicale-rca.onrender.com/transaction"
echo ""
echo "2. TEST COLLAPSE/EXPAND EXERCICES"
echo "   Action: Cliquer sur une ligne d'exercice (avec icône chevron)"
echo "   Résultat attendu: Les transactions de cet exercice se masquent"
echo "   Vérifier: https://amicale-rca.onrender.com/transaction"
echo ""
echo "===== TESTS À EFFECTUER MANUELLEMENT ====="
echo ""
echo "Test A: Filtre par Crédit"
echo "  1. Accéder à /transaction"
echo "  2. Sélectionner Type de montant: Crédit"
echo "  3. Cliquer sur 'Filtrer'"
echo "  4. Vérifier: Les montants cumulés restent corrects (devraient être différents de la vue sans filtre)"
echo ""
echo "Test B: Collapse/Expand"
echo "  1. Accéder à /transaction"
echo "  2. Cliquer sur une ligne d'exercice (avec chevron ↑)"
echo "  3. Vérifier: Les transactions se masquent et le chevron s'inverse (↓)"
echo "  4. Cliquer à nouveau pour dérouler"
echo "  5. Vérifier: Les transactions réapparaissent et le chevron se réinverse (↑)"
echo ""
echo "===== NOTES IMPORTANTES ====="
echo "- Le montant cumulé est pré-calculé depuis TOUTES les transactions"
echo "- Les filtres n'affectent que les transactions AFFICHÉES, pas les montants"
echo "- Le collapse/expand est géré par JavaScript dans transaction-page-scripts.js"
echo "- Vérifier la console navigateur (F12) pour des erreurs JavaScript"
echo ""
